const fs = require('fs');
const path = require('path');

const localesPath = './src/i18n/locales/soundbuttons';
const langs = ['en', 'es', 'fr', 'pt', 'ru', 'it', 'ja', 'ko', 'de'];

const translations = {
  en: {
    "seo.home_title": "{siteName}: Play, Download and Share the Best Sound Buttons Online",
    "seo.welcome_text": "Welcome to {siteNameCompact}, your one-stop shop for sound buttons, meme sounds, and soundboards that actually work without any hassle. Whether you're here to prank a friend, spice up a stream, or just click random sounds because it's fun, you're in the right place. No sign-ups, no annoying pop-ups, just sounds ready to play in one click.\n\nWe built this site to be fast, simple, and packed with the sounds people actually search for. So let's get into what sound buttons are all about, and why so many people keep coming back to click, laugh, and share.",
    "seo.q_meme_title": "What Is a Meme Soundboard?",
    "seo.q_meme_desc1": "A meme soundboard is basically a themed collection of sound buttons built around internet memes and viral moments. Think of clips from trending videos, funny reactions, or sounds that blew up on social media overnight.",
    "seo.q_meme_desc2": "Our meme soundboard collects all these trending sounds in one place so you don't have to dig through random videos trying to find that one sound everyone's using. It's organized, easy to browse, and updated often with whatever's currently making the rounds online.",
    "seo.q_buttons_title": "What are Sound Buttons?",
    "seo.q_buttons_desc1": "Sound buttons are exactly what they sound like. Small clickable buttons that play a short audio clip the moment you tap them. Could be a funny line from a show, a viral meme sound, an old school game effect, or just a weird noise that somehow became internet famous.",
    "seo.q_buttons_desc2": "The idea is simple. You click, it plays, you laugh or send it to a friend. That's the whole magic behind it. No downloads needed unless you want to keep the sound for later, and even that only takes one more click.",
    
    "seo.built_for_title": "Who Uses Sound Buttons?",
    "seo.built_for_subtitle": "Honestly, a lot more people than you'd think.",
    "seo.built_for.streamers_title": "Streamers",
    "seo.built_for.streamers_desc": "Streamers use them to react live on camera.",
    "seo.built_for.discord_title": "Content Creators",
    "seo.built_for.discord_desc": "Content creators drop them into videos for extra comedic timing.",
    "seo.built_for.students_title": "Friend Groups",
    "seo.built_for.students_desc": "Friend groups use them in voice chats just to mess with each other.",
    "seo.built_for.creators_title": "Teachers",
    "seo.built_for.creators_desc": "Even teachers have been known to sneak in a funny sound button to lighten up a boring class.",
    "seo.built_for.pranksters_title": "Casual Crowd",
    "seo.built_for.pranksters_desc": "People who just enjoy clicking through sounds because it's oddly satisfying. If you've ever found yourself clicking one sound after another with no real plan, you already know exactly what we mean.",
    
    "seo.extra.collection_title": "The Ultimate Meme Soundboard Collection",
    "seo.extra.collection_desc": "We've put together what we think is one of the biggest and most useful meme soundboard collections around. Clips from viral videos, classic internet jokes, trending audio, all sorted so you're not scrolling forever trying to find something good.\n\nNew meme sounds get added regularly too, so if you're someone who likes staying on top of whatever's trending, check the meme soundboard section often. Chances are, whatever sound just went viral is already sitting there waiting for you.",
    "seo.extra.stands_out_title": "Why Our Meme Soundboard Stands Out",
    "seo.extra.stands_out_desc": "There's a lot of soundboard sites out there, not gonna lie. But here's the thing, most of them are cluttered with ads, slow loading pages, or sounds that are outdated by months.\n\nOurs focuses on speed and simplicity. Clips load instantly, the layout is clean, and we keep things updated so you're not stuck listening to sounds that stopped being funny a year ago. Basically, we cut the noise and keep the actual sounds.",
    "seo.extra.unblocked_title": "What Is Meme Soundboard Unblocked?",
    "seo.extra.unblocked_desc": "A lot of people search for meme soundboard unblocked because they're trying to use sound buttons somewhere that usually blocks access to random websites, like school or work networks. Basically it means a soundboard site that still works even under restricted internet connections.\n\nGood news, our site is lightweight and doesn't rely on heavy downloads or shady scripts, so it tends to work fine in most places where other sites get blocked. Just keep in mind that network restrictions vary depending on where you're browsing from.",
    "seo.extra.popular_title": "Most Popular Meme Sound Buttons",
    "seo.extra.popular_desc": "Some sounds just never get old. The ones that everyone recognizes the second they hear the first half second of it. Those tend to be our most clicked buttons, and honestly, that says a lot.\n\nPopular meme sounds usually come from viral clips, funny movie lines, or reaction sounds that somehow became a whole internet moment. If you're not sure where to start, the meme soundboard is a solid first stop since it's basically a highlight reel of internet culture.",
    
    "seo.explore_categories_title": "Explore All Soundboard Categories",
    "seo.explore_categories_desc": "Memes are great, but they're not the only thing here. We've got categories covering everything from movie quotes to game sounds to random funny effects that don't fit anywhere else but somehow still get clicked constantly.\n\nBrowsing by category makes it way easier to find exactly what you're looking for instead of scrolling endlessly. And if you're the type who likes checking what's new, our latest sounds page gets updated regularly with fresh uploads across every category.",
    
    "seo.category.meme": "Meme Soundboard: Vine Boom, Bruh, Sad Hamster, Goofy Ahh, Nuh Uh and Skibidi, every viral audio that made internet history lives here.",
    "seo.category.effects": "Sound Effects Soundboard: Explosions, beeps, swooshes, foley and transitions, versatile audio built for creators and editors.",
    "seo.category.reaction": "Reaction Soundboard: Gasps, cheers, slow claps and awkward silences, the perfect reaction for every online moment.",
    "seo.category.tiktok": "TikTok Trends Soundboard: Whatever's blowing up on your FYP this week, already added and ready to play right away.",
    "seo.category.games": "Games Soundboard: Boss battle music, level up jingles and iconic in game cues that every gamer instantly recognizes.",
    "seo.category.anime": "Anime Soundboard: Legendary quotes, dramatic transformations and emotional stingers from the series everyone loves.",
    "seo.category.movies": "Movies Soundboard: Famous movie quotes, theme songs and classic film clips you can play instantly, anytime you want.",
    "seo.category.pranks": "Prank Soundboard: Jump scares, random noises and fake notifications, the full chaos starter pack for pranking friends.",
    "seo.category.politics": "Politics Soundboard: Timely clips and viral political moments, perfect for satire, commentary and quick reactions.",
    "seo.category.creativity": "Creativity Soundboard: Ambient sounds, inspiring cues and creative audio made for makers, designers and writers.",
    
    "seo.different_title": "Why {siteName} Is the Best for Sound Buttons",
    "seo.different_subtitle": "Most \"sound buttons\" sites are a mess. They're slow loading, packed with paywalls, have broken players, and honestly half the buttons turn out to be ads in disguise. We built {siteName} because we got tired of dealing with that too. Here's what you actually get:",
    "seo.different.points.1": "Massive library of sound buttons: You'll find viral meme clips, classic sound effects, TikTok audio, anime quotes, prank sounds and honestly a lot of weird stuff you didn't even know you needed.",
    "seo.different.points.2": "Instant playback: Every sound is optimised for a sub-second response, so you press it, hear it, and react right away.",
    "seo.different.points.3": "Unblocked, everywhere: It works on school WiFi, office networks and locked-down devices with no VPN and no proxy needed, just the site itself.",
    "seo.different.points.4": "Mobile-friendly: The site is built for thumbs, taps and phones first, so it works smoothly no matter what device you're on.",
    "seo.different.points.5": "New sounds added daily: If something just went viral, chances are it's already sitting on the site waiting for you.",
    "seo.different.points.6": "Safe and Clean: No annoying pop-ups, malicious ads, or shady downloads. Just pure entertainment.",
    
    "seo.faq_title": "Frequently Asked Questions",
    "seo.faq.q1": "Is {siteName} free to use?",
    "seo.faq.a1": "Yes, completely free. No subscriptions, no hidden fees.",
    "seo.faq.q2": "Is this a meme soundboard unblocked at school?",
    "seo.faq.a2": "yes. We don't use blocked embeds or flagged audio hosts, so {siteName} loads where most other soundboard sites fail.",
    "seo.faq.q3": "Can I download the sounds?",
    "seo.faq.a3": "Yes, most sound buttons have a simple download option right next to the play button.",
    "seo.faq.q4": "How often are new sounds added?",
    "seo.faq.a4": "Pretty often. Check the newest uploads page if you want to stay updated on fresh content.",
    "seo.faq.q5": "What is a meme soundboard used for?",
    "seo.faq.a5": "It's used to quickly find and play trending meme sounds, usually for streaming, content creation, or just messing around with friends."
  },
  es: {
    "seo.home_title": "{siteName}: Reproduce, descarga y comparte los mejores botones de sonido",
    "seo.welcome_text": "Bienvenido a {siteNameCompact}, tu tienda integral de botones de sonido...",
    "seo.q_meme_title": "¿Qué es un Meme Soundboard?",
    "seo.q_meme_desc1": "Es básicamente una colección temática de botones de sonido...",
    "seo.q_meme_desc2": "Nuestro meme soundboard recopila todos estos sonidos virales...",
    "seo.q_buttons_title": "¿Qué son los botones de sonido?",
    "seo.q_buttons_desc1": "Son exactamente lo que parecen. Pequeños botones en los que puedes hacer clic...",
    "seo.q_buttons_desc2": "La idea es simple. Haces clic, se reproduce, te ríes...",
    
    "seo.built_for_title": "¿Quién usa los botones de sonido?",
    "seo.built_for_subtitle": "Mucha más gente de la que crees.",
    "seo.built_for.streamers_title": "Streamers",
    "seo.built_for.streamers_desc": "Los usan para reaccionar en vivo.",
    "seo.built_for.discord_title": "Creadores de contenido",
    "seo.built_for.discord_desc": "Los agregan a sus videos para mayor sincronización cómica.",
    "seo.built_for.students_title": "Grupos de amigos",
    "seo.built_for.students_desc": "En chats de voz para molestarse entre sí.",
    "seo.built_for.creators_title": "Maestros",
    "seo.built_for.creators_desc": "Incluso algunos maestros los usan para alegrar una clase.",
    "seo.built_for.pranksters_title": "Público casual",
    "seo.built_for.pranksters_desc": "Personas que simplemente disfrutan haciendo clic en sonidos.",
    
    "seo.extra.collection_title": "La colección definitiva",
    "seo.extra.collection_desc": "Hemos reunido una de las colecciones más grandes.",
    "seo.extra.stands_out_title": "Por qué destaca nuestro Meme Soundboard",
    "seo.extra.stands_out_desc": "Se centra en la velocidad y la simplicidad.",
    "seo.extra.unblocked_title": "¿Qué es Meme Soundboard Unblocked?",
    "seo.extra.unblocked_desc": "Una plataforma que funciona en redes restringidas como escuelas.",
    "seo.extra.popular_title": "Botones de sonido más populares",
    "seo.extra.popular_desc": "Los sonidos que nunca envejecen.",
    
    "seo.explore_categories_title": "Explorar categorías",
    "seo.explore_categories_desc": "Navegar por categorías hace que sea más fácil encontrar lo que buscas.",
    
    "seo.category.meme": "Meme Soundboard: Todos los audios virales.",
    "seo.category.effects": "Efectos de sonido: Explosiones, pitidos y más.",
    "seo.category.reaction": "Reacciones: Jadeos, aplausos lentos.",
    "seo.category.tiktok": "Tendencias de TikTok: Lo que está de moda hoy.",
    "seo.category.games": "Juegos: Música de jefes y niveles.",
    "seo.category.anime": "Anime: Citas legendarias y transformaciones.",
    "seo.category.movies": "Películas: Citas famosas y bandas sonoras.",
    "seo.category.pranks": "Bromas: Sustos y notificaciones falsas.",
    "seo.category.politics": "Política: Momentos políticos virales.",
    "seo.category.creativity": "Creatividad: Sonidos ambientales y relajantes.",
    
    "seo.different_title": "Por qué {siteName} es el mejor",
    "seo.different_subtitle": "La mayoría de los sitios son un desastre. Aquí tienes lo que obtienes con nosotros:",
    "seo.different.points.1": "Biblioteca masiva de botones de sonido.",
    "seo.different.points.2": "Reproducción instantánea en menos de un segundo.",
    "seo.different.points.3": "Desbloqueado en todas partes (escuela, trabajo).",
    "seo.different.points.4": "Apto para dispositivos móviles.",
    "seo.different.points.5": "Nuevos sonidos añadidos a diario.",
    "seo.different.points.6": "Seguro y limpio, sin anuncios maliciosos.",
    
    "seo.faq_title": "Preguntas frecuentes",
    "seo.faq.q1": "¿Es {siteName} gratis?",
    "seo.faq.a1": "Sí, completamente gratis.",
    "seo.faq.q2": "¿Funciona en la escuela?",
    "seo.faq.a2": "Sí, carga donde otros sitios fallan.",
    "seo.faq.q3": "¿Puedo descargar los sonidos?",
    "seo.faq.a3": "Sí, hay una opción de descarga sencilla.",
    "seo.faq.q4": "¿Con qué frecuencia se agregan nuevos sonidos?",
    "seo.faq.a4": "Muy a menudo.",
    "seo.faq.q5": "¿Para qué se usa un meme soundboard?",
    "seo.faq.a5": "Para encontrar rápidamente sonidos en tendencia para streams o chats."
  },
  fr: {
    "seo.home_title": "{siteName} : Jouez, téléchargez et partagez",
    "seo.welcome_text": "Bienvenue sur {siteNameCompact}, votre destination unique pour les boutons sonores...",
    "seo.q_meme_title": "Qu'est-ce qu'une boîte à sons de mèmes ?",
    "seo.q_meme_desc1": "Une collection de boutons sonores thématiques...",
    "seo.q_meme_desc2": "Nous rassemblons tous ces sons viraux en un seul endroit.",
    "seo.q_buttons_title": "Que sont les boutons sonores ?",
    "seo.q_buttons_desc1": "De petits boutons cliquables qui jouent un court extrait audio...",
    "seo.q_buttons_desc2": "L'idée est simple. Vous cliquez, ça joue.",
    
    "seo.built_for_title": "Qui utilise les boutons sonores ?",
    "seo.built_for_subtitle": "Beaucoup plus de gens que vous ne le pensez.",
    "seo.built_for.streamers_title": "Streamers",
    "seo.built_for.streamers_desc": "Pour réagir en direct.",
    "seo.built_for.discord_title": "Créateurs de contenu",
    "seo.built_for.discord_desc": "Pour le timing comique.",
    "seo.built_for.students_title": "Groupes d'amis",
    "seo.built_for.students_desc": "Pour s'amuser en chat vocal.",
    "seo.built_for.creators_title": "Professeurs",
    "seo.built_for.creators_desc": "Pour détendre l'atmosphère en classe.",
    "seo.built_for.pranksters_title": "Utilisateurs occasionnels",
    "seo.built_for.pranksters_desc": "Ceux qui aiment juste cliquer.",
    
    "seo.extra.collection_title": "La collection ultime",
    "seo.extra.collection_desc": "Une des plus grandes bibliothèques du web.",
    "seo.extra.stands_out_title": "Pourquoi notre site se démarque",
    "seo.extra.stands_out_desc": "Nous misons sur la vitesse et la simplicité.",
    "seo.extra.unblocked_title": "Qu'est-ce qu'une boîte à sons débloquée ?",
    "seo.extra.unblocked_desc": "Un site qui fonctionne même sur les réseaux scolaires.",
    "seo.extra.popular_title": "Sons les plus populaires",
    "seo.extra.popular_desc": "Les classiques intemporels.",
    
    "seo.explore_categories_title": "Explorer les catégories",
    "seo.explore_categories_desc": "Trouvez rapidement ce que vous cherchez.",
    
    "seo.category.meme": "Mèmes : Tous les audios viraux.",
    "seo.category.effects": "Effets sonores : Explosions, bips.",
    "seo.category.reaction": "Réactions : Applaudissements lents.",
    "seo.category.tiktok": "TikTok : Les tendances du moment.",
    "seo.category.games": "Jeux : Musiques de boss.",
    "seo.category.anime": "Anime : Citations légendaires.",
    "seo.category.movies": "Films : Citations célèbres.",
    "seo.category.pranks": "Farces : Bruits effrayants.",
    "seo.category.politics": "Politique : Moments viraux.",
    "seo.category.creativity": "Créativité : Sons d'ambiance.",
    
    "seo.different_title": "Pourquoi {siteName} est le meilleur",
    "seo.different_subtitle": "La plupart des sites sont lents. Voici ce que nous offrons :",
    "seo.different.points.1": "Une bibliothèque massive.",
    "seo.different.points.2": "Lecture instantanée.",
    "seo.different.points.3": "Débloqué partout.",
    "seo.different.points.4": "Compatible mobile.",
    "seo.different.points.5": "Ajouts quotidiens.",
    "seo.different.points.6": "Propre et sécurisé.",
    
    "seo.faq_title": "Foire aux questions",
    "seo.faq.q1": "Est-ce gratuit ?",
    "seo.faq.a1": "Oui, 100% gratuit.",
    "seo.faq.q2": "Est-ce débloqué à l'école ?",
    "seo.faq.a2": "Oui, ça fonctionne partout.",
    "seo.faq.q3": "Puis-je télécharger les sons ?",
    "seo.faq.a3": "Oui, très facilement.",
    "seo.faq.q4": "À quelle fréquence ajoutez-vous des sons ?",
    "seo.faq.a4": "Très souvent.",
    "seo.faq.q5": "À quoi ça sert ?",
    "seo.faq.a5": "Pour s'amuser, réagir en stream, ou éditer des vidéos."
  },
  pt: {
    "seo.home_title": "{siteName}: O Melhor Site de Botões de Som",
    "seo.welcome_text": "Bem-vindo ao {siteNameCompact}...",
    "seo.q_meme_title": "O que é um Meme Soundboard?",
    "seo.q_meme_desc1": "Uma coleção de sons de memes...",
    "seo.q_meme_desc2": "Agrupamos tudo num só lugar.",
    "seo.q_buttons_title": "O que são Botões de Som?",
    "seo.q_buttons_desc1": "Pequenos botões que tocam áudio instantaneamente.",
    "seo.q_buttons_desc2": "Você clica e ri.",
    "seo.built_for_title": "Quem usa?",
    "seo.built_for_subtitle": "Muitas pessoas.",
    "seo.built_for.streamers_title": "Streamers",
    "seo.built_for.streamers_desc": "Para reações ao vivo.",
    "seo.built_for.discord_title": "Criadores",
    "seo.built_for.discord_desc": "Para vídeos divertidos.",
    "seo.built_for.students_title": "Amigos",
    "seo.built_for.students_desc": "Para zoar no chat.",
    "seo.built_for.creators_title": "Professores",
    "seo.built_for.creators_desc": "Para descontrair a aula.",
    "seo.built_for.pranksters_title": "Casuais",
    "seo.built_for.pranksters_desc": "Pessoas normais.",
    "seo.extra.collection_title": "A Maior Coleção",
    "seo.extra.collection_desc": "Milhares de sons virais.",
    "seo.extra.stands_out_title": "Por que nos Destacamos",
    "seo.extra.stands_out_desc": "Foco em velocidade.",
    "seo.extra.unblocked_title": "Desbloqueado?",
    "seo.extra.unblocked_desc": "Funciona em redes de escolas.",
    "seo.extra.popular_title": "Botões Mais Populares",
    "seo.extra.popular_desc": "Os sons que todo mundo ama.",
    "seo.explore_categories_title": "Categorias",
    "seo.explore_categories_desc": "Fácil de achar.",
    "seo.category.meme": "Memes.",
    "seo.category.effects": "Efeitos Sonoros.",
    "seo.category.reaction": "Reações.",
    "seo.category.tiktok": "TikTok.",
    "seo.category.games": "Jogos.",
    "seo.category.anime": "Animes.",
    "seo.category.movies": "Filmes.",
    "seo.category.pranks": "Pegadinhas.",
    "seo.category.politics": "Política.",
    "seo.category.creativity": "Criatividade.",
    "seo.different_title": "Por que o {siteName} é Melhor",
    "seo.different_subtitle": "Muitos sites são ruins. Nós somos rápidos.",
    "seo.different.points.1": "Muito áudio.",
    "seo.different.points.2": "Toca na hora.",
    "seo.different.points.3": "Desbloqueado.",
    "seo.different.points.4": "No celular.",
    "seo.different.points.5": "Sons novos sempre.",
    "seo.different.points.6": "Seguro.",
    "seo.faq_title": "FAQ",
    "seo.faq.q1": "Grátis?",
    "seo.faq.a1": "Sim.",
    "seo.faq.q2": "Funciona na escola?",
    "seo.faq.a2": "Sim.",
    "seo.faq.q3": "Dá pra baixar?",
    "seo.faq.a3": "Sim.",
    "seo.faq.q4": "Atualiza sempre?",
    "seo.faq.a4": "Sim.",
    "seo.faq.q5": "Pra que serve?",
    "seo.faq.a5": "Diversão."
  },
  ru: {
    "seo.home_title": "{siteName}: Лучшие звуковые кнопки онлайн",
    "seo.welcome_text": "Добро пожаловать на {siteNameCompact}...",
    "seo.q_meme_title": "Что такое Meme Soundboard?",
    "seo.q_meme_desc1": "Это коллекция вирусных звуков...",
    "seo.q_meme_desc2": "Все мемы в одном месте.",
    "seo.q_buttons_title": "Что такое звуковые кнопки?",
    "seo.q_buttons_desc1": "Маленькие кнопки для воспроизведения звуков.",
    "seo.q_buttons_desc2": "Нажал и посмеялся.",
    "seo.built_for_title": "Кто это использует?",
    "seo.built_for_subtitle": "Многие.",
    "seo.built_for.streamers_title": "Стримеры",
    "seo.built_for.streamers_desc": "Для реакций.",
    "seo.built_for.discord_title": "Креаторы",
    "seo.built_for.discord_desc": "Для видео.",
    "seo.built_for.students_title": "Друзья",
    "seo.built_for.students_desc": "В чатах.",
    "seo.built_for.creators_title": "Учителя",
    "seo.built_for.creators_desc": "В классе.",
    "seo.built_for.pranksters_title": "Обычные люди",
    "seo.built_for.pranksters_desc": "Ради шутки.",
    "seo.extra.collection_title": "Огромная коллекция",
    "seo.extra.collection_desc": "Тысячи звуков.",
    "seo.extra.stands_out_title": "Почему мы лучшие",
    "seo.extra.stands_out_desc": "Мы работаем быстро.",
    "seo.extra.unblocked_title": "Разблокированный Soundboard?",
    "seo.extra.unblocked_desc": "Работает в школах.",
    "seo.extra.popular_title": "Популярные звуки",
    "seo.extra.popular_desc": "Вечная классика.",
    "seo.explore_categories_title": "Категории",
    "seo.explore_categories_desc": "Все удобно разбито по темам.",
    "seo.category.meme": "Мемы.",
    "seo.category.effects": "Эффекты.",
    "seo.category.reaction": "Реакции.",
    "seo.category.tiktok": "TikTok.",
    "seo.category.games": "Игры.",
    "seo.category.anime": "Аниме.",
    "seo.category.movies": "Фильмы.",
    "seo.category.pranks": "Пранки.",
    "seo.category.politics": "Политика.",
    "seo.category.creativity": "Творчество.",
    "seo.different_title": "Почему {siteName} топ",
    "seo.different_subtitle": "Другие сайты тормозят. Мы — нет.",
    "seo.different.points.1": "Много звуков.",
    "seo.different.points.2": "Мгновенно.",
    "seo.different.points.3": "Без блокировок.",
    "seo.different.points.4": "С телефона.",
    "seo.different.points.5": "Каждый день новые.",
    "seo.different.points.6": "Безопасно.",
    "seo.faq_title": "FAQ",
    "seo.faq.q1": "Бесплатно?",
    "seo.faq.a1": "Да.",
    "seo.faq.q2": "В школе работает?",
    "seo.faq.a2": "Да.",
    "seo.faq.q3": "Можно скачать?",
    "seo.faq.a3": "Да.",
    "seo.faq.q4": "Часто обновляется?",
    "seo.faq.a4": "Постоянно.",
    "seo.faq.q5": "Зачем это?",
    "seo.faq.a5": "Для веселья."
  },
  it: {
    "seo.home_title": "{siteName}: I Migliori Pulsanti Sonori",
    "seo.welcome_text": "Benvenuto su {siteNameCompact}...",
    "seo.q_meme_title": "Cos'è una Meme Soundboard?",
    "seo.q_meme_desc1": "Una raccolta di suoni virali...",
    "seo.q_meme_desc2": "Tutti i trend in un posto.",
    "seo.q_buttons_title": "Cosa sono i pulsanti sonori?",
    "seo.q_buttons_desc1": "Piccoli pulsanti che riproducono clip audio.",
    "seo.q_buttons_desc2": "Un clic per ridere.",
    "seo.built_for_title": "Chi li utilizza?",
    "seo.built_for_subtitle": "Tante persone.",
    "seo.built_for.streamers_title": "Streamer",
    "seo.built_for.streamers_desc": "Per le live.",
    "seo.built_for.discord_title": "Creatori",
    "seo.built_for.discord_desc": "Per i video.",
    "seo.built_for.students_title": "Amici",
    "seo.built_for.students_desc": "Nelle chat vocali.",
    "seo.built_for.creators_title": "Insegnanti",
    "seo.built_for.creators_desc": "A scuola.",
    "seo.built_for.pranksters_title": "Casual",
    "seo.built_for.pranksters_desc": "Per divertimento.",
    "seo.extra.collection_title": "La Collezione Definitiva",
    "seo.extra.collection_desc": "Migliaia di suoni.",
    "seo.extra.stands_out_title": "Perché ci distinguiamo",
    "seo.extra.stands_out_desc": "Siamo veloci.",
    "seo.extra.unblocked_title": "Sbloccata ovunque",
    "seo.extra.unblocked_desc": "Funziona nelle scuole.",
    "seo.extra.popular_title": "I Più Popolari",
    "seo.extra.popular_desc": "I classici.",
    "seo.explore_categories_title": "Categorie",
    "seo.explore_categories_desc": "Facile da navigare.",
    "seo.category.meme": "Meme.",
    "seo.category.effects": "Effetti.",
    "seo.category.reaction": "Reazioni.",
    "seo.category.tiktok": "TikTok.",
    "seo.category.games": "Giochi.",
    "seo.category.anime": "Anime.",
    "seo.category.movies": "Film.",
    "seo.category.pranks": "Scherzi.",
    "seo.category.politics": "Politica.",
    "seo.category.creativity": "Creatività.",
    "seo.different_title": "Perché {siteName} è il Migliore",
    "seo.different_subtitle": "Siamo semplicemente superiori.",
    "seo.different.points.1": "Catalogo enorme.",
    "seo.different.points.2": "Audio istantaneo.",
    "seo.different.points.3": "Sbloccato.",
    "seo.different.points.4": "Su smartphone.",
    "seo.different.points.5": "Aggiornato ogni giorno.",
    "seo.different.points.6": "Sicuro.",
    "seo.faq_title": "FAQ",
    "seo.faq.q1": "Gratis?",
    "seo.faq.a1": "Sì.",
    "seo.faq.q2": "A scuola funziona?",
    "seo.faq.a2": "Sì.",
    "seo.faq.q3": "Posso scaricarli?",
    "seo.faq.a3": "Sì.",
    "seo.faq.q4": "Spesso aggiornati?",
    "seo.faq.a4": "Sì.",
    "seo.faq.q5": "A cosa servono?",
    "seo.faq.a5": "Per ridere."
  },
  ja: {
    "seo.home_title": "{siteName}: 最高のサウンドボタン",
    "seo.welcome_text": "{siteNameCompact}へようこそ...",
    "seo.q_meme_title": "ミームサウンドボードとは？",
    "seo.q_meme_desc1": "ネット上の話題の音声を集めたものです...",
    "seo.q_meme_desc2": "すべてが1か所に。",
    "seo.q_buttons_title": "サウンドボタンとは？",
    "seo.q_buttons_desc1": "クリックするだけで短い音声が流れるボタンです。",
    "seo.q_buttons_desc2": "クリックして笑うだけ。",
    "seo.built_for_title": "誰が使っているの？",
    "seo.built_for_subtitle": "多くの人が使っています。",
    "seo.built_for.streamers_title": "ストリーマー",
    "seo.built_for.streamers_desc": "配信中に。",
    "seo.built_for.discord_title": "クリエイター",
    "seo.built_for.discord_desc": "動画編集に。",
    "seo.built_for.students_title": "友達同士",
    "seo.built_for.students_desc": "チャットで。",
    "seo.built_for.creators_title": "先生",
    "seo.built_for.creators_desc": "授業で。",
    "seo.built_for.pranksters_title": "一般の人",
    "seo.built_for.pranksters_desc": "暇つぶしに。",
    "seo.extra.collection_title": "究極のコレクション",
    "seo.extra.collection_desc": "大量の音声。",
    "seo.extra.stands_out_title": "私たちのサイトが選ばれる理由",
    "seo.extra.stands_out_desc": "動作が軽快です。",
    "seo.extra.unblocked_title": "アンブロック版？",
    "seo.extra.unblocked_desc": "学校でも使えます。",
    "seo.extra.popular_title": "人気のサウンド",
    "seo.extra.popular_desc": "定番のサウンド。",
    "seo.explore_categories_title": "カテゴリー",
    "seo.explore_categories_desc": "探しやすく分類されています。",
    "seo.category.meme": "ミーム。",
    "seo.category.effects": "効果音。",
    "seo.category.reaction": "リアクション。",
    "seo.category.tiktok": "TikTok。",
    "seo.category.games": "ゲーム。",
    "seo.category.anime": "アニメ。",
    "seo.category.movies": "映画。",
    "seo.category.pranks": "イタズラ。",
    "seo.category.politics": "政治。",
    "seo.category.creativity": "クリエイティブ。",
    "seo.different_title": "{siteName} が最高の理由",
    "seo.different_subtitle": "私たちは他とは違います。",
    "seo.different.points.1": "膨大なライブラリ。",
    "seo.different.points.2": "瞬時に再生。",
    "seo.different.points.3": "制限なし。",
    "seo.different.points.4": "スマホ対応。",
    "seo.different.points.5": "毎日更新。",
    "seo.different.points.6": "安全。",
    "seo.faq_title": "FAQ",
    "seo.faq.q1": "無料ですか？",
    "seo.faq.a1": "はい。",
    "seo.faq.q2": "学校でも使えますか？",
    "seo.faq.a2": "はい。",
    "seo.faq.q3": "ダウンロードできますか？",
    "seo.faq.a3": "はい。",
    "seo.faq.q4": "更新頻度は？",
    "seo.faq.a4": "毎日です。",
    "seo.faq.q5": "どうやって使うの？",
    "seo.faq.a5": "楽しむために。"
  },
  ko: {
    "seo.home_title": "{siteName}: 최고의 사운드 버튼",
    "seo.welcome_text": "{siteNameCompact}에 오신 것을 환영합니다...",
    "seo.q_meme_title": "밈 사운드보드란?",
    "seo.q_meme_desc1": "인터넷 유행어와 사운드의 모음집...",
    "seo.q_meme_desc2": "한곳에 모여있습니다.",
    "seo.q_buttons_title": "사운드 버튼이란?",
    "seo.q_buttons_desc1": "클릭하면 짧은 오디오가 재생되는 버튼입니다.",
    "seo.q_buttons_desc2": "간단하게 즐기세요.",
    "seo.built_for_title": "누가 사용하나요?",
    "seo.built_for_subtitle": "많은 사람들이 사용합니다.",
    "seo.built_for.streamers_title": "스트리머",
    "seo.built_for.streamers_desc": "방송 중 리액션.",
    "seo.built_for.discord_title": "크리에이터",
    "seo.built_for.discord_desc": "영상 편집용.",
    "seo.built_for.students_title": "친구들",
    "seo.built_for.students_desc": "채팅방에서.",
    "seo.built_for.creators_title": "선생님",
    "seo.built_for.creators_desc": "수업 분위기 환기.",
    "seo.built_for.pranksters_title": "일반인",
    "seo.built_for.pranksters_desc": "재미로.",
    "seo.extra.collection_title": "궁극의 컬렉션",
    "seo.extra.collection_desc": "수많은 사운드.",
    "seo.extra.stands_out_title": "우리가 돋보이는 이유",
    "seo.extra.stands_out_desc": "빠르고 가볍습니다.",
    "seo.extra.unblocked_title": "언블락 사운드보드?",
    "seo.extra.unblocked_desc": "학교에서도 작동합니다.",
    "seo.extra.popular_title": "인기 사운드",
    "seo.extra.popular_desc": "유명한 사운드들.",
    "seo.explore_categories_title": "카테고리",
    "seo.explore_categories_desc": "찾기 쉽게 분류되었습니다.",
    "seo.category.meme": "밈.",
    "seo.category.effects": "효과음.",
    "seo.category.reaction": "리액션.",
    "seo.category.tiktok": "틱톡.",
    "seo.category.games": "게임.",
    "seo.category.anime": "애니.",
    "seo.category.movies": "영화.",
    "seo.category.pranks": "장난.",
    "seo.category.politics": "정치.",
    "seo.category.creativity": "창작.",
    "seo.different_title": "{siteName}이(가) 최고인 이유",
    "seo.different_subtitle": "다른 곳보다 뛰어납니다.",
    "seo.different.points.1": "거대한 라이브러리.",
    "seo.different.points.2": "즉각 재생.",
    "seo.different.points.3": "차단 없음.",
    "seo.different.points.4": "모바일 지원.",
    "seo.different.points.5": "매일 업데이트.",
    "seo.different.points.6": "안전함.",
    "seo.faq_title": "FAQ",
    "seo.faq.q1": "무료인가요?",
    "seo.faq.a1": "네.",
    "seo.faq.q2": "학교에서도 되나요?",
    "seo.faq.a2": "네.",
    "seo.faq.q3": "다운로드 가능해요?",
    "seo.faq.a3": "네.",
    "seo.faq.q4": "자주 업데이트 되나요?",
    "seo.faq.a4": "네.",
    "seo.faq.q5": "어디에 쓰나요?",
    "seo.faq.a5": "재미를 위해."
  },
  de: {
    "seo.home_title": "{siteName}: Die besten Sound-Buttons",
    "seo.welcome_text": "Willkommen bei {siteNameCompact}...",
    "seo.q_meme_title": "Was ist ein Meme-Soundboard?",
    "seo.q_meme_desc1": "Eine Sammlung viraler Internet-Sounds...",
    "seo.q_meme_desc2": "Alles an einem Ort.",
    "seo.q_buttons_title": "Was sind Sound-Buttons?",
    "seo.q_buttons_desc1": "Kleine Schaltflächen für Sounds.",
    "seo.q_buttons_desc2": "Einfach anklicken und lachen.",
    "seo.built_for_title": "Wer nutzt Sound-Buttons?",
    "seo.built_for_subtitle": "Viele Leute.",
    "seo.built_for.streamers_title": "Streamer",
    "seo.built_for.streamers_desc": "Für Live-Reaktionen.",
    "seo.built_for.discord_title": "Ersteller",
    "seo.built_for.discord_desc": "Für Videos.",
    "seo.built_for.students_title": "Freunde",
    "seo.built_for.students_desc": "In Sprachchats.",
    "seo.built_for.creators_title": "Lehrer",
    "seo.built_for.creators_desc": "Im Unterricht.",
    "seo.built_for.pranksters_title": "Normale Nutzer",
    "seo.built_for.pranksters_desc": "Zum Spaß.",
    "seo.extra.collection_title": "Die ultimative Sammlung",
    "seo.extra.collection_desc": "Tausende Sounds.",
    "seo.extra.stands_out_title": "Warum wir herausstechen",
    "seo.extra.stands_out_desc": "Wir sind schneller.",
    "seo.extra.unblocked_title": "Unblockiertes Soundboard?",
    "seo.extra.unblocked_desc": "Funktioniert in Schulen.",
    "seo.extra.popular_title": "Beliebteste Sounds",
    "seo.extra.popular_desc": "Die Klassiker.",
    "seo.explore_categories_title": "Kategorien",
    "seo.explore_categories_desc": "Leicht zu finden.",
    "seo.category.meme": "Memes.",
    "seo.category.effects": "Effekte.",
    "seo.category.reaction": "Reaktionen.",
    "seo.category.tiktok": "TikTok.",
    "seo.category.games": "Gaming.",
    "seo.category.anime": "Anime.",
    "seo.category.movies": "Filme.",
    "seo.category.pranks": "Streiche.",
    "seo.category.politics": "Politik.",
    "seo.category.creativity": "Kreativität.",
    "seo.different_title": "Warum {siteName} am besten ist",
    "seo.different_subtitle": "Wir sind einfach besser.",
    "seo.different.points.1": "Riesige Bibliothek.",
    "seo.different.points.2": "Sofortiges Abspielen.",
    "seo.different.points.3": "Unblockiert.",
    "seo.different.points.4": "Für Handys.",
    "seo.different.points.5": "Tägliche Updates.",
    "seo.different.points.6": "Sicher.",
    "seo.faq_title": "FAQ",
    "seo.faq.q1": "Kostenlos?",
    "seo.faq.a1": "Ja.",
    "seo.faq.q2": "Funktioniert es in der Schule?",
    "seo.faq.a2": "Ja.",
    "seo.faq.q3": "Kann ich herunterladen?",
    "seo.faq.a3": "Ja.",
    "seo.faq.q4": "Immer aktuell?",
    "seo.faq.a4": "Ja.",
    "seo.faq.q5": "Wofür nutzt man das?",
    "seo.faq.a5": "Für Spaß."
  }
};

for (const lang of langs) {
  const filePath = path.join(localesPath, `${lang}.json`);
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    Object.assign(data, translations[lang]);
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
    console.log(`Updated ${lang}.json`);
  } else {
    console.log(`File not found: ${filePath}`);
  }
}
