const fs = require('fs');
const path = require('path');

const localesPath = './src/i18n/locales/soundbuttons';
const langs = ['es', 'fr', 'pt', 'ru', 'it', 'ja', 'ko', 'de'];

const translations = {
  es: {
    "article.title": "{siteName}: Reproduce, descarga y comparte los mejores botones de sonido",
    "article.toc.title": "Tabla de contenido",
    "article.toc.intro": "Introducción",
    "article.toc.what_are_sound_buttons": "¿Qué son los botones de sonido?",
    "article.toc.what_is_meme_soundboard": "¿Qué es un Meme Soundboard?",
    "article.toc.who_uses": "¿Quién usa los botones de sonido?",
    "article.toc.ultimate_collection": "La colección definitiva de Meme Soundboard",
    "article.toc.why_ours_stands_out": "Por qué destaca nuestro Meme Soundboard",
    "article.toc.unblocked": "¿Qué es Meme Soundboard Unblocked?",
    "article.toc.most_popular": "Los botones de sonido de memes más populares",
    "article.toc.explore_categories": "Explorar todas las categorías",
    "article.toc.why_best": "Por qué {siteName} es el mejor",
    "article.toc.faq": "Preguntas frecuentes",
    "article.intro.title": "Introducción",
    "article.intro.p1": "Bienvenido a {siteNameCompact}, tu tienda integral de botones de sonido, sonidos de memes y cajas de resonancia que realmente funcionan sin problemas. Ya sea que estés aquí para gastar una broma, animar un stream o simplemente hacer clic en sonidos por diversión, estás en el lugar correcto. Sin registros ni ventanas emergentes molestas.",
    "article.intro.p2": "Construimos este sitio para que sea rápido, simple y esté lleno de los sonidos que la gente realmente busca. Así que entremos en materia.",
    "article.what_are_sound_buttons.title": "¿Qué son los botones de sonido?",
    "article.what_are_sound_buttons.p1": "Son exactamente lo que parecen. Pequeños botones en los que puedes hacer clic y que reproducen un clip de audio corto al tocarlos.",
    "article.what_are_sound_buttons.p2": "La idea es simple. Haces clic, se reproduce, te ríes o se lo envías a un amigo.",
    "article.what_is_meme_soundboard.title": "¿Qué es un Meme Soundboard?",
    "article.what_is_meme_soundboard.p1": "Es básicamente una colección temática de botones de sonido creados a partir de memes de Internet y momentos virales.",
    "article.what_is_meme_soundboard.p2": "Nuestro meme soundboard recopila todos estos sonidos virales en un solo lugar.",
    "article.who_uses.title": "¿Quién usa los botones de sonido?",
    "article.who_uses.p1": "Honestamente, mucha más gente de la que crees. Los streamers los usan en vivo. Los creadores de contenido los agregan a sus videos. Los grupos de amigos los usan en el chat de voz.",
    "article.who_uses.p2": "Y luego está el público casual. Personas que simplemente disfrutan haciendo clic en sonidos porque es extrañamente satisfactorio.",
    "article.ultimate_collection.title": "La colección definitiva de Meme Soundboard",
    "article.ultimate_collection.p1": "Hemos reunido lo que creemos que es una de las colecciones más grandes y útiles de la web.",
    "article.ultimate_collection.p2": "También agregamos nuevos sonidos regularmente, así que vuelve a menudo.",
    "article.why_ours_stands_out.title": "Por qué destaca nuestro Meme Soundboard",
    "article.why_ours_stands_out.p1": "Hay muchos sitios por ahí, pero la mayoría están llenos de anuncios, tardan en cargar o tienen sonidos desactualizados.",
    "article.why_ours_stands_out.p2": "El nuestro se centra en la velocidad y la simplicidad. Los clips cargan al instante.",
    "article.unblocked.title": "¿Qué es Meme Soundboard Unblocked?",
    "article.unblocked.p1": "Mucha gente busca esto porque intentan usar botones de sonido en lugares con redes restringidas, como la escuela o el trabajo.",
    "article.unblocked.p2": "Nuestra plataforma es ligera y no depende de scripts sospechosos, por lo que tiende a funcionar bien en la mayoría de lugares.",
    "article.most_popular.title": "Los botones de sonido de memes más populares",
    "article.most_popular.p1": "Algunos sonidos nunca envejecen. Esos suelen ser nuestros botones con más clics.",
    "article.most_popular.p2": "Los sonidos populares suelen provenir de clips virales o frases de películas.",
    "article.explore_categories.title": "Explorar todas las categorías",
    "article.explore_categories.p1": "Los memes son geniales, pero no son lo único que tenemos. Tenemos categorías que abarcan desde frases de películas hasta efectos de juegos.",
    "article.explore_categories.p2": "Navegar por categorías hace que sea mucho más fácil encontrar exactamente lo que buscas.",
    "article.why_best.title": "Por qué {siteName} es el mejor para botones de sonido",
    "article.why_best.p1": "La mayoría de los sitios son un desastre. Construimos {siteName} porque nos cansamos de lidiar con eso. Esto es lo que obtienes:",
    "article.why_best.l1_title": "Biblioteca masiva:",
    "article.why_best.l1_desc": " Encontrarás clips virales, efectos clásicos y audios de TikTok.",
    "article.why_best.l2_title": "Reproducción instantánea:",
    "article.why_best.l2_desc": " Cada sonido está optimizado para una respuesta de menos de un segundo.",
    "article.why_best.l3_title": "Desbloqueado, en todas partes:",
    "article.why_best.l3_desc": " Funciona en el WiFi de la escuela y redes de oficina sin necesidad de VPN.",
    "article.why_best.l4_title": "Apto para dispositivos móviles:",
    "article.why_best.l4_desc": " Funciona sin problemas sin importar en qué dispositivo estés.",
    "article.why_best.l5_title": "Nuevos sonidos a diario:",
    "article.why_best.l5_desc": " Si algo se vuelve viral, lo encontrarás aquí.",
    "article.faq.title": "Preguntas frecuentes",
    "article.faq.q1": "¿Es {siteName} gratis?",
    "article.faq.a1": "Sí, completamente gratis. Sin suscripciones ni tarifas ocultas.",
    "article.faq.q2": "¿Es un meme soundboard desbloqueado en la escuela?",
    "article.faq.a2": "Sí, evitamos hosts bloqueados para que cargue donde otros fallan.",
    "article.faq.q3": "¿Puedo descargar los sonidos?",
    "article.faq.a3": "Sí, la mayoría de los botones tienen una opción de descarga sencilla.",
    "article.faq.q4": "¿Con qué frecuencia se agregan nuevos sonidos?",
    "article.faq.a4": "Muy a menudo. Revisa la página de últimas incorporaciones para mantenerte actualizado.",
    "article.faq.q5": "¿Para qué se usa un meme soundboard?",
    "article.faq.a5": "Se usa para encontrar y reproducir sonidos en tendencia, ideal para streams y chats."
  },
  fr: {
    "article.title": "{siteName} : Jouez, téléchargez et partagez les meilleurs boutons sonores",
    "article.toc.title": "Table des matières",
    "article.toc.intro": "Introduction",
    "article.toc.what_are_sound_buttons": "Que sont les boutons sonores ?",
    "article.toc.what_is_meme_soundboard": "Qu'est-ce qu'une boîte à sons de mèmes ?",
    "article.toc.who_uses": "Qui utilise les boutons sonores ?",
    "article.toc.ultimate_collection": "La collection ultime",
    "article.toc.why_ours_stands_out": "Pourquoi notre site se démarque",
    "article.toc.unblocked": "Qu'est-ce qu'une boîte à sons débloquée ?",
    "article.toc.most_popular": "Boutons sonores les plus populaires",
    "article.toc.explore_categories": "Explorer toutes les catégories",
    "article.toc.why_best": "Pourquoi {siteName} est le meilleur",
    "article.toc.faq": "Foire aux questions",
    "article.intro.title": "Introduction",
    "article.intro.p1": "Bienvenue sur {siteNameCompact}, votre destination unique pour les boutons sonores, les sons de mèmes et les boîtes à sons qui fonctionnent sans problème. Aucun téléchargement requis, aucune fenêtre pop-up ennuyeuse.",
    "article.intro.p2": "Nous avons conçu ce site pour qu'il soit rapide et regorge des sons que les gens recherchent vraiment.",
    "article.what_are_sound_buttons.title": "Que sont les boutons sonores ?",
    "article.what_are_sound_buttons.p1": "De petits boutons cliquables qui jouent un court extrait audio dès que vous appuyez dessus.",
    "article.what_are_sound_buttons.p2": "L'idée est simple. Vous cliquez, ça joue, vous riez.",
    "article.what_is_meme_soundboard.title": "Qu'est-ce qu'une boîte à sons de mèmes ?",
    "article.what_is_meme_soundboard.p1": "Une collection de boutons sonores thématiques autour des mèmes Internet et des moments viraux.",
    "article.what_is_meme_soundboard.p2": "Nous rassemblons tous ces sons au même endroit pour éviter de chercher partout.",
    "article.who_uses.title": "Qui utilise les boutons sonores ?",
    "article.who_uses.p1": "Des streamers, des créateurs de contenu, et même des amis lors de discussions vocales.",
    "article.who_uses.p2": "Et puis il y a la foule occasionnelle qui clique pour s'amuser.",
    "article.ultimate_collection.title": "La collection ultime",
    "article.ultimate_collection.p1": "L'une des plus vastes collections d'effets sonores viraux.",
    "article.ultimate_collection.p2": "De nouveaux sons sont ajoutés régulièrement pour rester à l'affût des tendances.",
    "article.why_ours_stands_out.title": "Pourquoi notre site se démarque",
    "article.why_ours_stands_out.p1": "Beaucoup de sites sont lents et remplis de publicités.",
    "article.why_ours_stands_out.p2": "Notre plateforme est ultra-rapide et mise à jour régulièrement.",
    "article.unblocked.title": "Qu'est-ce qu'une boîte à sons débloquée ?",
    "article.unblocked.p1": "Cela permet aux utilisateurs sous réseaux restreints (écoles, bureaux) d'y accéder.",
    "article.unblocked.p2": "Notre site léger contourne les limitations pour fonctionner partout.",
    "article.most_popular.title": "Boutons sonores les plus populaires",
    "article.most_popular.p1": "Les classiques intemporels sont souvent les plus cliqués.",
    "article.most_popular.p2": "Nos sons les plus populaires incluent des phrases de films et des mèmes cultes.",
    "article.explore_categories.title": "Explorer toutes les catégories",
    "article.explore_categories.p1": "Les mèmes sont géniaux, mais nous avons aussi des jeux, des films et plus encore.",
    "article.explore_categories.p2": "Les catégories vous permettent de naviguer facilement.",
    "article.why_best.title": "Pourquoi {siteName} est le meilleur",
    "article.why_best.p1": "Nous avons créé {siteName} parce que nous en avions assez des sites lents. Voici ce que nous offrons :",
    "article.why_best.l1_title": "Bibliothèque massive :",
    "article.why_best.l1_desc": " Des extraits viraux, classiques et bruits inattendus.",
    "article.why_best.l2_title": "Lecture instantanée :",
    "article.why_best.l2_desc": " Lecture ultra-rapide en un clic.",
    "article.why_best.l3_title": "Débloqué partout :",
    "article.why_best.l3_desc": " Fonctionne sur les réseaux scolaires et de travail sans VPN.",
    "article.why_best.l4_title": "Compatible mobile :",
    "article.why_best.l4_desc": " Parfaitement adapté pour les smartphones.",
    "article.why_best.l5_title": "Ajouts quotidiens :",
    "article.why_best.l5_desc": " Nouveaux sons de mèmes chaque jour.",
    "article.faq.title": "Foire aux questions",
    "article.faq.q1": "Est-ce gratuit ?",
    "article.faq.a1": "Oui, 100% gratuit, sans abonnement.",
    "article.faq.q2": "Est-ce débloqué à l'école ?",
    "article.faq.a2": "Oui, ça fonctionne là où les autres sites échouent.",
    "article.faq.q3": "Puis-je télécharger les sons ?",
    "article.faq.a3": "Oui, via le bouton de téléchargement simple.",
    "article.faq.q4": "À quelle fréquence ajoutez-vous des sons ?",
    "article.faq.a4": "Très souvent, nous suivons les tendances virales.",
    "article.faq.q5": "À quoi ça sert ?",
    "article.faq.a5": "Pour s'amuser, réagir en stream, ou éditer des vidéos."
  },
  pt: {
    "article.title": "{siteName}: Reproduza, Baixe e Compartilhe os Melhores Botões de Som",
    "article.toc.title": "Índice",
    "article.toc.intro": "Introdução",
    "article.toc.what_are_sound_buttons": "O que são Botões de Som?",
    "article.toc.what_is_meme_soundboard": "O que é um Meme Soundboard?",
    "article.toc.who_uses": "Quem usa Botões de Som?",
    "article.toc.ultimate_collection": "A Maior Coleção de Meme Soundboard",
    "article.toc.why_ours_stands_out": "Por que nos Destacamos",
    "article.toc.unblocked": "Meme Soundboard Desbloqueado?",
    "article.toc.most_popular": "Botões Mais Populares",
    "article.toc.explore_categories": "Explorar Categorias",
    "article.toc.why_best": "Por que o {siteName} é o Melhor",
    "article.toc.faq": "Perguntas Frequentes",
    "article.intro.title": "Introdução",
    "article.intro.p1": "Bem-vindo ao {siteNameCompact}, a melhor plataforma de botões de som e memes. Tudo sem anúncios irritantes e sem registro.",
    "article.intro.p2": "Construímos este site para ser rápido e direto ao ponto.",
    "article.what_are_sound_buttons.title": "O que são Botões de Som?",
    "article.what_are_sound_buttons.p1": "São pequenos botões clicáveis que tocam um clipe de áudio instantaneamente.",
    "article.what_are_sound_buttons.p2": "É só clicar, ouvir e rir.",
    "article.what_is_meme_soundboard.title": "O que é um Meme Soundboard?",
    "article.what_is_meme_soundboard.p1": "Uma coleção organizada de sons de memes da internet e clipes virais.",
    "article.what_is_meme_soundboard.p2": "Organizamos tudo num só lugar para facilitar sua vida.",
    "article.who_uses.title": "Quem usa Botões de Som?",
    "article.who_uses.p1": "Streamers, criadores de conteúdo no TikTok/YouTube e gamers no Discord.",
    "article.who_uses.p2": "E também qualquer um que queira rir de sons engraçados.",
    "article.ultimate_collection.title": "A Maior Coleção de Meme Soundboard",
    "article.ultimate_collection.p1": "Temos uma das maiores bibliotecas da web.",
    "article.ultimate_collection.p2": "Sons virais são adicionados regularmente.",
    "article.why_ours_stands_out.title": "Por que nos Destacamos",
    "article.why_ours_stands_out.p1": "Muitos sites são lentos e lotados de anúncios.",
    "article.why_ours_stands_out.p2": "Nosso site foca em velocidade, carregando clipes na hora.",
    "article.unblocked.title": "O que é Meme Soundboard Desbloqueado?",
    "article.unblocked.p1": "Muitas redes escolares e empresariais bloqueiam sites de entretenimento.",
    "article.unblocked.p2": "Nossa plataforma é leve e consegue passar por esses bloqueios facilmente.",
    "article.most_popular.title": "Os Botões de Memes Mais Populares",
    "article.most_popular.p1": "Alguns sons são eternos. Esses são os mais clicados.",
    "article.most_popular.p2": "Seja uma fala famosa ou um grito viral.",
    "article.explore_categories.title": "Explorar Categorias",
    "article.explore_categories.p1": "Temos memes, frases de filmes, efeitos sonoros para edição e mais.",
    "article.explore_categories.p2": "As categorias facilitam a navegação pelo site.",
    "article.why_best.title": "Por que {siteName} é o Melhor",
    "article.why_best.p1": "Construímos o {siteName} para resolver todos os problemas de outros sites. Aqui você tem:",
    "article.why_best.l1_title": "Biblioteca Gigante:",
    "article.why_best.l1_desc": " Milhares de opções para todas as situações.",
    "article.why_best.l2_title": "Reprodução Imediata:",
    "article.why_best.l2_desc": " O som toca sem nenhum atraso.",
    "article.why_best.l3_title": "Desbloqueado:",
    "article.why_best.l3_desc": " Funciona na escola e no trabalho.",
    "article.why_best.l4_title": "Pronto para Celular:",
    "article.why_best.l4_desc": " Use perfeitamente no seu smartphone.",
    "article.why_best.l5_title": "Atualizações Diárias:",
    "article.why_best.l5_desc": " Tendências adicionadas a todo momento.",
    "article.faq.title": "Perguntas Frequentes",
    "article.faq.q1": "É grátis?",
    "article.faq.a1": "Sim, totalmente sem custos.",
    "article.faq.q2": "Funciona na escola?",
    "article.faq.a2": "Sim, é otimizado para evitar bloqueios.",
    "article.faq.q3": "Posso baixar os sons?",
    "article.faq.a3": "Sim, basta clicar no ícone de download.",
    "article.faq.q4": "Com que frequência atualizam?",
    "article.faq.a4": "Quase todos os dias adicionamos novos virais.",
    "article.faq.q5": "Para que serve?",
    "article.faq.a5": "Para reagir, editar vídeos ou zoar no chat de voz."
  },
  ru: {
    "article.title": "{siteName}: Лучшие звуковые кнопки онлайн",
    "article.toc.title": "Содержание",
    "article.toc.intro": "Введение",
    "article.toc.what_are_sound_buttons": "Что такое звуковые кнопки?",
    "article.toc.what_is_meme_soundboard": "Что такое Meme Soundboard?",
    "article.toc.who_uses": "Кто это использует?",
    "article.toc.ultimate_collection": "Огромная коллекция мемов",
    "article.toc.why_ours_stands_out": "Почему мы лучшие",
    "article.toc.unblocked": "Разблокированный Soundboard",
    "article.toc.most_popular": "Популярные звуки",
    "article.toc.explore_categories": "Категории звуков",
    "article.toc.why_best": "Почему {siteName} топ",
    "article.toc.faq": "Частые вопросы",
    "article.intro.title": "Введение",
    "article.intro.p1": "Добро пожаловать на {siteNameCompact} — лучший сайт со звуковыми кнопками. Никаких регистраций, просто жми и слушай.",
    "article.intro.p2": "Мы сделали этот сайт быстрым и удобным для всех.",
    "article.what_are_sound_buttons.title": "Что такое звуковые кнопки?",
    "article.what_are_sound_buttons.p1": "Это маленькие кнопки, которые при нажатии проигрывают короткий звук или мем.",
    "article.what_are_sound_buttons.p2": "Всё просто: нажал, послушал, отправил другу.",
    "article.what_is_meme_soundboard.title": "Что такое Meme Soundboard?",
    "article.what_is_meme_soundboard.p1": "Это коллекция вирусных звуков и мемов из интернета.",
    "article.what_is_meme_soundboard.p2": "Мы собрали их все в одном месте для вашего удобства.",
    "article.who_uses.title": "Кто это использует?",
    "article.who_uses.p1": "Стримеры, создатели видео на YouTube, геймеры в Discord.",
    "article.who_uses.p2": "А также обычные люди, которым нравится кликать и смеяться.",
    "article.ultimate_collection.title": "Огромная коллекция мемов",
    "article.ultimate_collection.p1": "У нас одна из самых больших баз звуков в сети.",
    "article.ultimate_collection.p2": "Новые звуки добавляются каждый день.",
    "article.why_ours_stands_out.title": "Почему мы лучшие",
    "article.why_ours_stands_out.p1": "Другие сайты тормозят и полны рекламы.",
    "article.why_ours_stands_out.p2": "Наш сайт работает мгновенно и без зависаний.",
    "article.unblocked.title": "Что значит Разблокированный Soundboard?",
    "article.unblocked.p1": "Это значит, что наш сайт работает даже там, где другие заблокированы (в школе или на работе).",
    "article.unblocked.p2": "Мы используем легкие скрипты, чтобы обходить ограничения.",
    "article.most_popular.title": "Самые популярные звуки",
    "article.most_popular.p1": "Некоторые звуки стали легендарными.",
    "article.most_popular.p2": "Это классика интернета, которая всегда актуальна.",
    "article.explore_categories.title": "Категории звуков",
    "article.explore_categories.p1": "У нас есть не только мемы, но и звуки из игр, фильмов и эффекты.",
    "article.explore_categories.p2": "Выбирай нужную категорию и наслаждайся.",
    "article.why_best.title": "Почему {siteName} топ",
    "article.why_best.p1": "Мы решили все проблемы других сайтов. Вот почему мы лучше:",
    "article.why_best.l1_title": "Огромная база:",
    "article.why_best.l1_desc": " Тысячи звуков на любой вкус.",
    "article.why_best.l2_title": "Мгновенное воспроизведение:",
    "article.why_best.l2_desc": " Без задержек и лагов.",
    "article.why_best.l3_title": "Работает везде:",
    "article.why_best.l3_desc": " Обходит блокировки Wi-Fi в школе и на работе.",
    "article.why_best.l4_title": "Удобно на телефоне:",
    "article.why_best.l4_desc": " Идеально для смартфонов.",
    "article.why_best.l5_title": "Новые звуки каждый день:",
    "article.why_best.l5_desc": " Все вирусные тренды сразу у нас.",
    "article.faq.title": "Часто задаваемые вопросы",
    "article.faq.q1": "Это бесплатно?",
    "article.faq.a1": "Да, абсолютно бесплатно.",
    "article.faq.q2": "Работает ли сайт в школе?",
    "article.faq.a2": "Да, он оптимизирован для обхода школьных блокировок.",
    "article.faq.q3": "Можно ли скачать звуки?",
    "article.faq.a3": "Да, скачивайте в формате MP3.",
    "article.faq.q4": "Как часто добавляют звуки?",
    "article.faq.a4": "Почти каждый день.",
    "article.faq.q5": "Для чего нужны эти звуки?",
    "article.faq.a5": "Для видео, стримов, мемов и просто ради шутки."
  },
  it: {
    "article.title": "{siteName}: Ascolta, Scarica e Condividi i Migliori Pulsanti Sonori",
    "article.toc.title": "Sommario",
    "article.toc.intro": "Introduzione",
    "article.toc.what_are_sound_buttons": "Cosa sono i pulsanti sonori?",
    "article.toc.what_is_meme_soundboard": "Cos'è una Meme Soundboard?",
    "article.toc.who_uses": "Chi li utilizza?",
    "article.toc.ultimate_collection": "La Collezione Definitiva",
    "article.toc.why_ours_stands_out": "Perché ci distinguiamo",
    "article.toc.unblocked": "Soundboard Sbloccata",
    "article.toc.most_popular": "I Più Popolari",
    "article.toc.explore_categories": "Esplora le Categorie",
    "article.toc.why_best": "Perché {siteName} è il Migliore",
    "article.toc.faq": "Domande Frequenti",
    "article.intro.title": "Introduzione",
    "article.intro.p1": "Benvenuto su {siteNameCompact}, la tua risorsa per i migliori meme e suoni.",
    "article.intro.p2": "Abbiamo creato questo sito per essere rapido e semplice.",
    "article.what_are_sound_buttons.title": "Cosa sono i pulsanti sonori?",
    "article.what_are_sound_buttons.p1": "Sono piccoli pulsanti che riproducono clip audio in un istante.",
    "article.what_are_sound_buttons.p2": "Basta un clic per ridere e divertirsi.",
    "article.what_is_meme_soundboard.title": "Cos'è una Meme Soundboard?",
    "article.what_is_meme_soundboard.p1": "Una raccolta organizzata di suoni virali.",
    "article.what_is_meme_soundboard.p2": "Tutti i trend in un unico posto.",
    "article.who_uses.title": "Chi li utilizza?",
    "article.who_uses.p1": "Streamer, creatori di contenuti e giocatori.",
    "article.who_uses.p2": "Anche le persone comuni in chat.",
    "article.ultimate_collection.title": "La Collezione Definitiva",
    "article.ultimate_collection.p1": "Una libreria enorme di meme e clip audio.",
    "article.ultimate_collection.p2": "Sempre aggiornata.",
    "article.why_ours_stands_out.title": "Perché ci distinguiamo",
    "article.why_ours_stands_out.p1": "Zero pubblicità invasive e massima velocità.",
    "article.why_ours_stands_out.p2": "Audio istantaneo.",
    "article.unblocked.title": "Cos'è la Soundboard Sbloccata?",
    "article.unblocked.p1": "Funziona anche nelle reti limitate (scuole, uffici).",
    "article.unblocked.p2": "Non si blocca come gli altri siti.",
    "article.most_popular.title": "I Più Popolari",
    "article.most_popular.p1": "I meme più classici di sempre.",
    "article.most_popular.p2": "I suoni più usati.",
    "article.explore_categories.title": "Esplora le Categorie",
    "article.explore_categories.p1": "Giochi, film, reazioni e molto altro.",
    "article.explore_categories.p2": "Tutto catalogato.",
    "article.why_best.title": "Perché {siteName} è il Migliore",
    "article.why_best.p1": "Ecco cosa ci rende speciali:",
    "article.why_best.l1_title": "Grande catalogo:",
    "article.why_best.l1_desc": " Meme, effetti e citazioni.",
    "article.why_best.l2_title": "Veloce:",
    "article.why_best.l2_desc": " Senza lag.",
    "article.why_best.l3_title": "Sbloccato:",
    "article.why_best.l3_desc": " Funziona ovunque.",
    "article.why_best.l4_title": "Ottimo su smartphone:",
    "article.why_best.l4_desc": " Perfetto da mobile.",
    "article.why_best.l5_title": "Sempre nuovo:",
    "article.why_best.l5_desc": " Aggiornamenti continui.",
    "article.faq.title": "Domande Frequenti",
    "article.faq.q1": "È gratis?",
    "article.faq.a1": "Sì, sempre gratuito.",
    "article.faq.q2": "Funziona a scuola?",
    "article.faq.a2": "Sì, la piattaforma aggira i blocchi.",
    "article.faq.q3": "Posso scaricarli?",
    "article.faq.a3": "Sì, in formato MP3.",
    "article.faq.q4": "Ogni quanto aggiornate?",
    "article.faq.a4": "Quasi ogni giorno.",
    "article.faq.q5": "A cosa serve?",
    "article.faq.a5": "Divertimento, streaming e video editing."
  },
  ja: {
    "article.title": "{siteName}: 最高のサウンドボタンを再生、ダウンロード、シェア",
    "article.toc.title": "目次",
    "article.toc.intro": "はじめに",
    "article.toc.what_are_sound_buttons": "サウンドボタンとは？",
    "article.toc.what_is_meme_soundboard": "ミームサウンドボードとは？",
    "article.toc.who_uses": "誰が使っているの？",
    "article.toc.ultimate_collection": "究極のコレクション",
    "article.toc.why_ours_stands_out": "私たちのサイトが選ばれる理由",
    "article.toc.unblocked": "アンブロック版サウンドボードとは？",
    "article.toc.most_popular": "人気のサウンド",
    "article.toc.explore_categories": "カテゴリーを見る",
    "article.toc.why_best": "{siteName} が最高の理由",
    "article.toc.faq": "よくある質問",
    "article.intro.title": "はじめに",
    "article.intro.p1": "{siteNameCompact}へようこそ。最高のミームサウンドと効果音が揃っています。",
    "article.intro.p2": "使いやすく、高速で動作します。",
    "article.what_are_sound_buttons.title": "サウンドボタンとは？",
    "article.what_are_sound_buttons.p1": "クリックするだけで短い音声が流れるボタンです。",
    "article.what_are_sound_buttons.p2": "クリックして笑い、友達にシェアしましょう。",
    "article.what_is_meme_soundboard.title": "ミームサウンドボードとは？",
    "article.what_is_meme_soundboard.p1": "ネット上の話題の音声を集めたものです。",
    "article.what_is_meme_soundboard.p2": "すべてが1か所にまとまっています。",
    "article.who_uses.title": "誰が使っているの？",
    "article.who_uses.p1": "ストリーマー、動画クリエイター、ゲーマーなど。",
    "article.who_uses.p2": "友達とのチャットでも活躍します。",
    "article.ultimate_collection.title": "究極のコレクション",
    "article.ultimate_collection.p1": "ネット上のあらゆるミームサウンドを網羅。",
    "article.ultimate_collection.p2": "日々新しいサウンドが追加されています。",
    "article.why_ours_stands_out.title": "私たちのサイトが選ばれる理由",
    "article.why_ours_stands_out.p1": "広告が少なく、動作が軽快です。",
    "article.why_ours_stands_out.p2": "瞬時に音声が再生されます。",
    "article.unblocked.title": "アンブロック版サウンドボードとは？",
    "article.unblocked.p1": "学校や職場のネットワークでも利用できるという意味です。",
    "article.unblocked.p2": "ブロックされにくい仕組みになっています。",
    "article.most_popular.title": "人気のサウンド",
    "article.most_popular.p1": "おなじみの名言や効果音。",
    "article.most_popular.p2": "誰もが知っている定番サウンド。",
    "article.explore_categories.title": "カテゴリーを見る",
    "article.explore_categories.p1": "アニメ、ゲーム、映画など様々なカテゴリがあります。",
    "article.explore_categories.p2": "簡単に目当ての音声を見つけられます。",
    "article.why_best.title": "{siteName} が最高の理由",
    "article.why_best.p1": "私たちが最高の環境を提供します：",
    "article.why_best.l1_title": "膨大なライブラリ:",
    "article.why_best.l1_desc": " ありとあらゆる効果音。",
    "article.why_best.l2_title": "瞬時に再生:",
    "article.why_best.l2_desc": " タイムラグなし。",
    "article.why_best.l3_title": "制限なし:",
    "article.why_best.l3_desc": " どこでも使えます。",
    "article.why_best.l4_title": "スマホ対応:",
    "article.why_best.l4_desc": " タップしやすい設計。",
    "article.why_best.l5_title": "毎日更新:",
    "article.why_best.l5_desc": " トレンドを逃しません。",
    "article.faq.title": "よくある質問",
    "article.faq.q1": "無料ですか？",
    "article.faq.a1": "はい、完全無料です。",
    "article.faq.q2": "学校でも使えますか？",
    "article.faq.a2": "はい、多くの制限されたネットワークで動作します。",
    "article.faq.q3": "ダウンロードできますか？",
    "article.faq.a3": "はい、MP3で保存可能です。",
    "article.faq.q4": "更新頻度は？",
    "article.faq.a4": "ほぼ毎日新しい音声を追加しています。",
    "article.faq.q5": "どうやって使うの？",
    "article.faq.a5": "動画編集やチャットのリアクションに最適です。"
  },
  ko: {
    "article.title": "{siteName}: 최고의 사운드 버튼 재생, 다운로드 및 공유",
    "article.toc.title": "목차",
    "article.toc.intro": "소개",
    "article.toc.what_are_sound_buttons": "사운드 버튼이란?",
    "article.toc.what_is_meme_soundboard": "밈 사운드보드란?",
    "article.toc.who_uses": "누가 사용하나요?",
    "article.toc.ultimate_collection": "궁극의 컬렉션",
    "article.toc.why_ours_stands_out": "우리가 돋보이는 이유",
    "article.toc.unblocked": "언블락 사운드보드란?",
    "article.toc.most_popular": "인기 사운드",
    "article.toc.explore_categories": "카테고리 탐색",
    "article.toc.why_best": "{siteName}이(가) 최고인 이유",
    "article.toc.faq": "자주 묻는 질문",
    "article.intro.title": "소개",
    "article.intro.p1": "{siteNameCompact}에 오신 것을 환영합니다. 모든 밈 소리를 한 곳에서 만나보세요.",
    "article.intro.p2": "매우 빠르고 사용하기 쉽습니다.",
    "article.what_are_sound_buttons.title": "사운드 버튼이란?",
    "article.what_are_sound_buttons.p1": "클릭하면 짧은 오디오가 재생되는 버튼입니다.",
    "article.what_are_sound_buttons.p2": "간단하게 즐기고 공유할 수 있습니다.",
    "article.what_is_meme_soundboard.title": "밈 사운드보드란?",
    "article.what_is_meme_soundboard.p1": "인터넷 유행어와 사운드의 모음집입니다.",
    "article.what_is_meme_soundboard.p2": "모든 유행을 한눈에 확인할 수 있습니다.",
    "article.who_uses.title": "누가 사용하나요?",
    "article.who_uses.p1": "스트리머, 크리에이터, 게이머들이 사용합니다.",
    "article.who_uses.p2": "일반 사용자들도 재미로 즐깁니다.",
    "article.ultimate_collection.title": "궁극의 컬렉션",
    "article.ultimate_collection.p1": "인터넷 상의 모든 밈을 보유하고 있습니다.",
    "article.ultimate_collection.p2": "항상 최신 상태로 유지됩니다.",
    "article.why_ours_stands_out.title": "우리가 돋보이는 이유",
    "article.why_ours_stands_out.p1": "광고가 적고 로딩이 빠릅니다.",
    "article.why_ours_stands_out.p2": "즉각적인 반응 속도를 자랑합니다.",
    "article.unblocked.title": "언블락 사운드보드란?",
    "article.unblocked.p1": "학교나 직장 같은 차단된 환경에서도 접속 가능합니다.",
    "article.unblocked.p2": "원활하게 작동하도록 설계되었습니다.",
    "article.most_popular.title": "인기 사운드",
    "article.most_popular.p1": "시간이 지나도 사랑받는 사운드.",
    "article.most_popular.p2": "모두가 아는 클래식 사운드입니다.",
    "article.explore_categories.title": "카테고리 탐색",
    "article.explore_categories.p1": "애니메이션, 게임, 영화 등 다양합니다.",
    "article.explore_categories.p2": "쉽게 원하는 소리를 찾을 수 있습니다.",
    "article.why_best.title": "{siteName}이(가) 최고인 이유",
    "article.why_best.p1": "우리는 최고의 환경을 제공합니다:",
    "article.why_best.l1_title": "거대한 라이브러리:",
    "article.why_best.l1_desc": " 모든 사운드가 있습니다.",
    "article.why_best.l2_title": "즉각 재생:",
    "article.why_best.l2_desc": " 딜레이가 없습니다.",
    "article.why_best.l3_title": "어디서나 접속:",
    "article.why_best.l3_desc": " 차단 없이 사용하세요.",
    "article.why_best.l4_title": "모바일 친화적:",
    "article.why_best.l4_desc": " 스마트폰에서도 완벽합니다.",
    "article.why_best.l5_title": "매일 업데이트:",
    "article.why_best.l5_desc": " 트렌드를 놓치지 않습니다.",
    "article.faq.title": "자주 묻는 질문",
    "article.faq.q1": "무료인가요?",
    "article.faq.a1": "네, 100% 무료입니다.",
    "article.faq.q2": "학교에서도 되나요?",
    "article.faq.a2": "네, 차단 시스템을 우회합니다.",
    "article.faq.q3": "다운로드 가능해요?",
    "article.faq.a3": "MP3로 저장할 수 있습니다.",
    "article.faq.q4": "얼마나 자주 업데이트 되나요?",
    "article.faq.a4": "매일 새로운 사운드가 추가됩니다.",
    "article.faq.q5": "어디에 쓰나요?",
    "article.faq.a5": "영상 편집이나 재미있는 리액션에 사용합니다."
  },
  de: {
    "article.title": "{siteName}: Spiele, lade herunter und teile die besten Sound-Buttons",
    "article.toc.title": "Inhaltsverzeichnis",
    "article.toc.intro": "Einführung",
    "article.toc.what_are_sound_buttons": "Was sind Sound-Buttons?",
    "article.toc.what_is_meme_soundboard": "Was ist ein Meme-Soundboard?",
    "article.toc.who_uses": "Wer nutzt Sound-Buttons?",
    "article.toc.ultimate_collection": "Die ultimative Sammlung",
    "article.toc.why_ours_stands_out": "Warum wir herausstechen",
    "article.toc.unblocked": "Was ist ein unblockiertes Soundboard?",
    "article.toc.most_popular": "Die beliebtesten Sounds",
    "article.toc.explore_categories": "Alle Kategorien erkunden",
    "article.toc.why_best": "Warum {siteName} am besten ist",
    "article.toc.faq": "Häufig gestellte Fragen",
    "article.intro.title": "Einführung",
    "article.intro.p1": "Willkommen bei {siteNameCompact}, deiner Anlaufstelle für die besten Meme-Sounds und Effekte.",
    "article.intro.p2": "Wir haben diese Seite schnell und werbefrei gestaltet.",
    "article.what_are_sound_buttons.title": "Was sind Sound-Buttons?",
    "article.what_are_sound_buttons.p1": "Kleine Schaltflächen, die auf Klick einen Sound abspielen.",
    "article.what_are_sound_buttons.p2": "Einfach anklicken und lachen.",
    "article.what_is_meme_soundboard.title": "Was ist ein Meme-Soundboard?",
    "article.what_is_meme_soundboard.p1": "Eine Sammlung viraler Internet-Sounds.",
    "article.what_is_meme_soundboard.p2": "Alle Trends an einem Ort.",
    "article.who_uses.title": "Wer nutzt Sound-Buttons?",
    "article.who_uses.p1": "Streamer, Video-Cutter und Gamer.",
    "article.who_uses.p2": "Und jeder, der Spaß an Memes hat.",
    "article.ultimate_collection.title": "Die ultimative Sammlung",
    "article.ultimate_collection.p1": "Wir bieten eine der größten Bibliotheken im Netz.",
    "article.ultimate_collection.p2": "Immer aktuell mit neuen Sounds.",
    "article.why_ours_stands_out.title": "Warum wir herausstechen",
    "article.why_ours_stands_out.p1": "Schnelle Ladezeiten und keine nervigen Popups.",
    "article.why_ours_stands_out.p2": "Sofortige Wiedergabe ohne Verzögerung.",
    "article.unblocked.title": "Was ist ein unblockiertes Soundboard?",
    "article.unblocked.p1": "Funktioniert auch in Schul- und Firmennetzwerken.",
    "article.unblocked.p2": "Unsere Seite umgeht gängige Sperren.",
    "article.most_popular.title": "Die beliebtesten Sounds",
    "article.most_popular.p1": "Zeitlose Klassiker und bekannte Zitate.",
    "article.most_popular.p2": "Die Sounds, die jeder kennt.",
    "article.explore_categories.title": "Alle Kategorien erkunden",
    "article.explore_categories.p1": "Anime, Gaming, Filme und mehr.",
    "article.explore_categories.p2": "Finde schnell, wonach du suchst.",
    "article.why_best.title": "Warum {siteName} am besten ist",
    "article.why_best.p1": "Hier ist, was wir bieten:",
    "article.why_best.l1_title": "Riesige Bibliothek:",
    "article.why_best.l1_desc": " Tausende Sounds.",
    "article.why_best.l2_title": "Sofortiges Abspielen:",
    "article.why_best.l2_desc": " Keine Wartezeit.",
    "article.why_best.l3_title": "Unblockiert:",
    "article.why_best.l3_desc": " Immer erreichbar.",
    "article.why_best.l4_title": "Mobilfreundlich:",
    "article.why_best.l4_desc": " Perfekt für Smartphones.",
    "article.why_best.l5_title": "Tägliche Updates:",
    "article.why_best.l5_desc": " Neue Trends sofort verfügbar.",
    "article.faq.title": "Häufig gestellte Fragen",
    "article.faq.q1": "Ist es kostenlos?",
    "article.faq.a1": "Ja, 100% gratis.",
    "article.faq.q2": "Funktioniert es in der Schule?",
    "article.faq.a2": "Ja, es ist für alle Netzwerke optimiert.",
    "article.faq.q3": "Kann ich Sounds herunterladen?",
    "article.faq.a3": "Ja, als MP3-Dateien.",
    "article.faq.q4": "Wie oft kommen neue Sounds?",
    "article.faq.a4": "Fast täglich.",
    "article.faq.q5": "Wofür nutzt man das?",
    "article.faq.a5": "Für lustige Chats, Streams und Videobearbeitung."
  }
};

for (const lang of langs) {
  const filePath = path.join(localesPath, `${lang}.json`);
  if (fs.existsSync(filePath)) {
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    Object.assign(data, translations[lang]);
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
    console.log(`Updated ${lang}.json`);
  } else {
    console.log(`File not found: ${filePath}`);
  }
}
